# Generated by Django 4.0.3 on 2022-03-25 13:58

from django.db import migrations
import home.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articlepage_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', home.blocks.CustomRichTextBlock()), ('image', home.blocks.CustomImageChooserBlock(icon='image'))]),
        ),
    ]
