# Generated by Django 4.0.3 on 2022-03-25 13:59

from django.db import migrations
import home.blocks
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_articlepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', home.blocks.CustomRichTextBlock()), ('image', home.blocks.CustomImageChooserBlock(icon='image')), ('table', wagtail.contrib.table_block.blocks.TableBlock())]),
        ),
    ]
